name: GCP Cloud Run
on: [push]
jobs:
  deploy:
    env:
      APP_NAME: reactapp
      CLOUDSDK_CORE_PROJECT: ao00-254402
      GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mapfap/gcloud/fastcli@master
      with:
        args: builds submit --tag gcr.io/$CLOUDSDK_CORE_PROJECT/$APP_NAME
    - uses: mapfap/gcloud/fastcli@master
      with:
        args: beta run deploy $APP_NAME --image gcr.io/$CLOUDSDK_CORE_PROJECT/$APP_NAME --platform managed --region asia-northeast1
